name: armor
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  google_fonts: ^6.2.0
  flutter_svg: ^2.0.10+1
  carousel_slider: ^4.2.1
  webview_flutter_web: ^0.2.2+4
  url_launcher: ^6.2.6
  google_generative_ai: ^0.3.3
  flutter_speed_dial: ^7.0.0
  firebase_core: ^2.31.0
  speech_to_text: ^6.6.1
  text_to_speech: ^0.2.3
  flutter_native_splash: ^2.4.0
  flutter_markdown: ^0.7.1
  webview_flutter: ^4.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:

  uses-material-design: true

  # assets:
  #   - assets/vectors/
  #   - assets/images/
  #   - assets/images/Story1/
  #   - assets/images/Story2/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

flutter_native_splash:
  color: '#061223'
  image: 'assets/images/logo.png'